# Generated by Django 2.1.2 on 2018-11-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextDoor', '0004_auto_20181116_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='subject',
            field=models.CharField(max_length=150),
        ),
    ]
