# Generated by Django 2.1.2 on 2018-11-16 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NextDoor', '0013_auto_20181116_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
