# Generated by Django 2.1.2 on 2018-11-16 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextDoor', '0015_auto_20181117_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 11, 17, 1, 11, 11, 475573)),
        ),
    ]
