# Generated by Django 2.1.2 on 2018-11-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NextDoor', '0018_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='title',
        ),
    ]
