# Generated by Django 2.1.2 on 2018-11-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NextDoor', '0020_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NextDoor.Group'),
            preserve_default=False,
        ),
    ]
