# Generated by Django 2.1.3 on 2018-11-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NextDoor', '0009_auto_20181116_2240'),
        ('NextDoor', '0021_announcement_group'),
    ]

    operations = [
    ]
