# Generated by Django 2.1.2 on 2018-11-22 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NextDoor', '0026_auto_20181122_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NextDoor.Group'),
        ),
    ]
