# Generated by Django 2.1.2 on 2018-12-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextDoor', '0027_auto_20181122_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='password',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
