# Generated by Django 2.1.2 on 2018-12-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextDoor', '0028_group_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
