# Generated by Django 2.1.2 on 2018-12-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NextDoor', '0029_auto_20181203_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='faculty_description',
        ),
    ]
